# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.8.3


# INSTALLATION
#################################################################

# WordPress version
wpversion: latest

# language/timezone
wplocale: en_US
timezone: "America/New_York"

# admin user settings
admin:
  user: admin
  password: admin
  email: mail@domain.tld
  first_name: "Admin"
  last_name: "Admin"

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: t34m42_

# SETTINGS
#################################################################

wpsettings:
  url: development.wp
  title: Example Title
  description: Example Description
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
  # define frontpage name (requires `page_on_front: true`)
  frontpage_name: Example Front Page
  # automatic conversion of smilies
  convert_smilies: false

# THEMES
#################################################################

# install a custom theme via url, rename it and remove the default themes
theme:
  name: base-theme
  url: "https://github.com/Suhkha/base-theme/archive/master.zip"
  rename: ""
  remove:
    - twentyfifteen
    - twentysixteen
    - twentyseventeen


# PLUGINS
#################################################################

# plugins to install & activate
#plugins_active:
  #- url-to-download-plugin.zip

# plugins to install
#plugins_inactive:

#plugins_delete:
  #- name-of-plugin

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: false
  cleanup: false
  # adjust what data you want to be deleted within the cleanup (requires `cleanup: true`)
  comment: false
  posts: false
  files: false
